resources:
  - name: containers-src
    type: git
    source:
      uri: https://github.com/tlwr/containers.git
      branch: main

  - name: rspec-podman-img
    type: registry-image
    icon: docker
    source:
      repository: ghcr.io/tlwr/rspec-podman
      username: ((docker-secrets.username))
      password: ((docker-secrets.password))

jobs:
  - name: set-pipeline
    serial: true
    plan:
      - get: containers-src
        trigger: true

      - set_pipeline: containers
        file: containers-src/ci/pipeline.yml

  - name: build-rspec-podman
    serial: true
    plan:
      - get: containers-src
        passed: [set-pipeline]
        trigger: true

      - task: build-image
        privileged: true
        config:
          platform: linux

          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task

          inputs:
            - name: containers-src
              path: .

          outputs:
            - name: image

          run:
            path: build

          caches:
            - path: cache

          params:
            CONTEXT: ./rspec-podman

      - put: rspec-podman-img
        params:
          image: image/image.tar
          additional_tags: containers-src/.git/ref
        get_params:
          skip_download: true

  - name: test-rspec-podman
    serial: true
    plan:
      - get: containers-src
        passed: [build-rspec-podman]

      - get: rspec-podman-img
        passed: [build-rspec-podman]
        trigger: true
        params:
          format: oci

      - task: test-image
        image: rspec-podman-img
        privileged: true
        config:
          platform: linux

          inputs:
            - name: containers-src

            - name: rspec-podman-img

          run:
            dir: containers-src
            path: rspec
            args: [rspec-podman]

          env:
            CONTAINER_PATH: ../rspec-podman-img/image.tar
